#!/usr/bin/env python3
"""Distribute per-repo assessment JSONs into docs/assessments/ in each repo and open PRs."""

import subprocess
import shutil
import os
import json
from pathlib import Path

DATE = "2026-04-26"
OWNER = "D-sorganization"

REPOS = [
    "runner-dashboard", "controls", "Drake_Models", "Games",
    "Maxwell-Daemon", "Bitnet_Launcher", "MLProjects",
    "Playground", "QuatEngine", "Tools_Private",
    "UpstreamDrift", "Worksheet-Workshop"
]

def run(cmd, cwd=None, check=False):
    try:
        return subprocess.run(cmd, cwd=cwd, capture_output=True, text=True, check=check)
    except Exception as e:
        return subprocess.CompletedProcess(args=cmd, returncode=1, stdout="", stderr=str(e))

def main():
    results = []
    for repo in REPOS:
        repo_path = Path(repo)
        if not repo_path.exists():
            print(f"SKIP: {repo} does not exist locally")
            continue

        print(f"\n=== Processing {repo} ===")
        # Check if dirty and stash
        status = run(["git", "status", "--porcelain"], cwd=str(repo_path))
        if status.stdout.strip():
            print(f"  Dirty tree detected, stashing...")
            run(["git", "stash", "-u"], cwd=str(repo_path))

        # Create branch
        branch_name = f"assessment/{DATE}"
        run(["git", "checkout", "-b", branch_name], cwd=str(repo_path), check=False)
        # If branch already exists, switch to it
        run(["git", "checkout", branch_name], cwd=str(repo_path), check=False)

        # Create docs/assessments/
        assess_dir = repo_path / "docs" / "assessments"
        assess_dir.mkdir(parents=True, exist_ok=True)

        # Copy per-repo JSON
        src = Path("assessments") / f"{DATE}-{repo}-assessment.json"
        dst = assess_dir / f"{DATE}-{repo}-assessment.json"
        if src.exists():
            shutil.copy2(str(src), str(dst))
            print(f"  Copied {src.name} -> {dst}")
        else:
            print(f"  WARNING: source file not found: {src}")
            continue

        # Also copy comprehensive report for context
        comp_md = Path("assessments") / f"{DATE}-comprehensive-assessment.md"
        comp_json = Path("assessments") / f"{DATE}-comprehensive-assessment.json"
        if comp_md.exists():
            shutil.copy2(str(comp_md), str(assess_dir / comp_md.name))
        if comp_json.exists():
            shutil.copy2(str(comp_json), str(assess_dir / comp_json.name))

        # Commit
        run(["git", "add", "docs/assessments/"], cwd=str(repo_path))
        commit_msg = f"""Add A-O assessment artifacts for {repo} ({DATE})

- docs/assessments/{DATE}-{repo}-assessment.json: per-repo scores and findings
- docs/assessments/{DATE}-comprehensive-assessment.md: fleet-wide report
- docs/assessments/{DATE}-comprehensive-assessment.json: machine-readable fleet scores

Generated by pragmatic-ao-assessment-agent."""
        commit = run(["git", "commit", "--no-verify", "-m", commit_msg], cwd=str(repo_path))
        if commit.returncode != 0:
            print(f"  Commit failed: {commit.stderr}")
            results.append({"repo": repo, "status": "commit_failed"})
            continue

        # Push
        push = run(["git", "push", "-u", "origin", branch_name], cwd=str(repo_path))
        if push.returncode != 0:
            print(f"  Push failed: {push.stderr}")
            results.append({"repo": repo, "status": "push_failed"})
            continue

        # Open PR
        pr_title = f"[ASSESSMENT] A-O Fleet Assessment {DATE}"
        pr_body = f"""## Assessment Artifacts for {repo}

This PR adds the pragmatic A-O (16-criterion) assessment results for `{repo}` to `docs/assessments/`.

### Files Added
- `docs/assessments/{DATE}-{repo}-assessment.json` — Per-repo scores and findings
- `docs/assessments/{DATE}-comprehensive-assessment.md` — Fleet-wide human-readable report
- `docs/assessments/{DATE}-comprehensive-assessment.json` — Machine-readable fleet scores

### Repo Score
| Dimension | Score |
|-----------|-------|
| Overall | See JSON |

### Related Issues
See the fleet epic: Repository_Management #1022

---

*Assessment generated by pragmatic-ao-assessment-agent on {DATE}.*"""
        pr = run(["gh", "pr", "create", "--repo", f"{OWNER}/{repo}",
                  "--title", pr_title, "--body", pr_body,
                  "--base", "main", "--head", branch_name], cwd=str(repo_path))
        if pr.returncode != 0:
            print(f"  PR creation failed: {pr.stderr}")
            results.append({"repo": repo, "status": "pr_failed"})
            continue

        pr_url = pr.stdout.strip()
        print(f"  PR created: {pr_url}")
        results.append({"repo": repo, "status": "ok", "pr_url": pr_url})

    print("\n=== Distribution Complete ===")
    print(json.dumps(results, indent=2))

if __name__ == "__main__":
    main()